package core_java_pro_employee;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class empform extends javax.swing.JFrame {

    /** Creates new form empform */
    public empform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopmsg = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        phtf = new javax.swing.JTextField();
        designtf = new javax.swing.JTextField();
        enametf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ecodetf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        depttf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bptf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        brb = new javax.swing.JRadioButton();
        arb = new javax.swing.JRadioButton();
        crb = new javax.swing.JRadioButton();
        drb = new javax.swing.JRadioButton();
        grtf = new javax.swing.JTextField();
        addrtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE PAYROLL MANAGEMENT");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("EMPLOYEE CODE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("DESIGNATION");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NAME");

        phtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phtfActionPerformed(evt);
            }
        });

        designtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designtfActionPerformed(evt);
            }
        });

        enametf.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel7.setText("ADDITION OF EMPLOYEES");

        addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("PHONE NO.");

        ecodetf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ecodetfFocusLost(evt);
            }
        });
        ecodetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecodetfActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DEPARTMENT");

        depttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depttfActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("BASIC PAY");

        bptf.setEditable(false);
        bptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bptfActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("GRADE ");

        buttonGroup1.add(brb);
        brb.setText("B");
        brb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brbActionPerformed(evt);
            }
        });

        buttonGroup1.add(arb);
        arb.setText("A");
        arb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arbActionPerformed(evt);
            }
        });

        buttonGroup1.add(crb);
        crb.setText("C");
        crb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crbActionPerformed(evt);
            }
        });

        buttonGroup1.add(drb);
        drb.setText("D");
        drb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drbActionPerformed(evt);
            }
        });

        grtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grtfActionPerformed(evt);
            }
        });

        addrtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrtfActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ADDRESS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel7)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(addbtn)
                        .addGap(61, 61, 61)
                        .addComponent(exitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel6))
                                                .addComponent(jLabel4)))))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designtf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enametf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(brb))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(arb)
                                        .addGap(51, 51, 51)
                                        .addComponent(crb)
                                        .addGap(18, 18, 18)
                                        .addComponent(drb)))
                                .addGap(18, 18, 18)
                                .addComponent(grtf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phtf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addrtf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bptf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                            .addComponent(depttf, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(enametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(designtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(crb)
                    .addComponent(arb)
                    .addComponent(drb)
                    .addComponent(brb)
                    .addComponent(grtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(depttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(exitbtn))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection cn=null;
ResultSet rs=null;
Statement stmt=null;
PreparedStatement pst = null;
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try
        {
            System.out.println("========");
     Class.forName("com.mysql.jdbc.Driver");
cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");
JOptionPane.showMessageDialog(new JFrame(),"database connected");


pst=cn.prepareStatement("insert into info values(?,?,?,?,?,?,?,?)");
pst.setString(1,ecodetf.getText());
pst.setString(2, enametf.getText());
pst.setString(3,designtf.getText());
pst.setString(4, grtf.getText());
pst.setString(5, depttf.getText());
pst.setString(6,bptf.getText());
pst.setString(7,addrtf.getText());
pst.setString(8,phtf.getText());
System.out.println("=================");

      pst.executeUpdate();
pst.close();
cn.close();
 jopmsg.showMessageDialog(null,"Employee ADDED","ADDITION OF RECORDS",1);
          
        } catch( Exception e){
            jopmsg.showMessageDialog(null,"ERROR IN CONNECTIVITY");}
}//GEN-LAST:event_addbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        salform sf=new salform();
        sf.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_exitbtnActionPerformed

    private void ecodetfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ecodetfFocusLost
    }//GEN-LAST:event_ecodetfFocusLost

    private void arbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arbActionPerformed
if (arb.isSelected())
        grtf.setText("Grade A");
        bptf.setText(""+18000);
    }//GEN-LAST:event_arbActionPerformed

    private void brbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brbActionPerformed
        if (brb.isSelected())
            grtf.setText("Grade B");
        bptf.setText(""+15000);
    }//GEN-LAST:event_brbActionPerformed

    private void crbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crbActionPerformed
       if (crb.isSelected())
           grtf.setText("Grade C");
        bptf.setText(""+12000);
    }//GEN-LAST:event_crbActionPerformed

    private void drbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drbActionPerformed
        if (drb.isSelected())
            grtf.setText("Grade D");
        bptf.setText(""+10000);
    }//GEN-LAST:event_drbActionPerformed

    private void ecodetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecodetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecodetfActionPerformed

    private void designtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designtfActionPerformed

    private void grtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grtfActionPerformed

    private void depttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depttfActionPerformed

    private void bptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bptfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bptfActionPerformed

    private void addrtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrtfActionPerformed

    private void phtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phtfActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField addrtf;
    private javax.swing.JRadioButton arb;
    private javax.swing.JTextField bptf;
    private javax.swing.JRadioButton brb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton crb;
    private javax.swing.JTextField depttf;
    private javax.swing.JTextField designtf;
    private javax.swing.JRadioButton drb;
    private javax.swing.JTextField ecodetf;
    private javax.swing.JTextField enametf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField grtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jopmsg;
    private javax.swing.JTextField phtf;
    // End of variables declaration//GEN-END:variables

}
