package core_java_pro_employee;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * empmenu.java
 *
 * Created on 25 Nov, 2013, 8:38:14 PM
 */

/**
 *
 * @author Harish
 */
public class empmenu extends javax.swing.JFrame {

    /** Creates new form empmenu */
    public empmenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reprb = new javax.swing.JRadioButton();
        emprb = new javax.swing.JRadioButton();
        processrb = new javax.swing.JRadioButton();
        exitrb = new javax.swing.JRadioButton();
        salrb = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE PAYROLL MANAGEMENT");

        reprb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reprb.setText("REPORTS");
        reprb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reprbActionPerformed(evt);
            }
        });

        emprb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emprb.setText("ADDITION OF EMPLOYEE");
        emprb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprbActionPerformed(evt);
            }
        });

        processrb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        processrb.setText("EMPLOYEE PROCESSING");
        processrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processrbActionPerformed(evt);
            }
        });

        exitrb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitrb.setText("EXIT");
        exitrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitrbActionPerformed(evt);
            }
        });

        salrb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salrb.setText("SALARY BILL");
        salrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salrbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE PAYROLL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reprb)
                            .addComponent(emprb)
                            .addComponent(processrb)
                            .addComponent(exitrb)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(salrb))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emprb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salrb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(processrb)
                .addGap(18, 18, 18)
                .addComponent(reprb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitrb)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reprbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reprbActionPerformed
        if(reprb.isSelected()) {
            reports rp = new reports();
            rp.setVisible(true);
            this.setVisible(false);
        }
}//GEN-LAST:event_reprbActionPerformed

    private void emprbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprbActionPerformed
        if(emprb.isSelected()) {
          empform emp = new empform();
            emp.setVisible(true);
            this.setVisible(false);
        }
}//GEN-LAST:event_emprbActionPerformed

    private void processrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processrbActionPerformed
        if(processrb.isSelected()) {
           empprocess pro = new empprocess();
            pro.setVisible(true);
            this.setVisible(false);
        }
}//GEN-LAST:event_processrbActionPerformed

    private void exitrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitrbActionPerformed
        thankz t=new thankz();
        t.setVisible(true);
        this.dispose();
}//GEN-LAST:event_exitrbActionPerformed

    private void salrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salrbActionPerformed
        if(salrb.isSelected()) {
            salform sal = new salform();
            sal.setVisible(true);
            this.setVisible(false);
        }
}//GEN-LAST:event_salrbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton emprb;
    private javax.swing.JRadioButton exitrb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton processrb;
    private javax.swing.JRadioButton reprb;
    private javax.swing.JRadioButton salrb;
    // End of variables declaration//GEN-END:variables

}
