package core_java_pro_employee;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * salform.java
 *
 * Created on 25 Nov, 2013, 11:02:43 PM
 */

/**
 *
 * @author Harish
 */
public class salform extends javax.swing.JFrame {

    /** Creates new form salform */
    public salform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jopmsg = new javax.swing.JOptionPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hratf = new javax.swing.JTextField();
        medtf = new javax.swing.JTextField();
        bptf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ecodecmb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pftf = new javax.swing.JTextField();
        contf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pttf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ittf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totearntf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totdedtf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        netpaytf = new javax.swing.JTextField();
        calcbtn = new javax.swing.JButton();
        ecodebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        ecodetf = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE PAYROLL MANAGEMENT");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("EMPLOYEE CODE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("BASIC PAY");

        hratf.setEditable(false);

        medtf.setEditable(false);

        bptf.setEditable(false);
        bptf.setToolTipText("");
        bptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bptfActionPerformed(evt);
            }
        });
        bptf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bptfFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("MEDICAL ALLOWANCE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("HOUSE RENT ALLOWANCE");

        ecodecmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecodecmbActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CONVEYANCE ALLOWANCE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PROVIDENT FUND");

        pftf.setEditable(false);

        contf.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("PROFESSIONAL TAX");

        pttf.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("INCOME TAX");

        ittf.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("TOTAL EARNINGS");

        totearntf.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("TOTAL DEDUCTIONS");

        totdedtf.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("NET PAY");

        netpaytf.setEditable(false);

        calcbtn.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        calcbtn.setText("CALCULATE NET PAY");
        calcbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calcbtnFocusGained(evt);
            }
        });
        calcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbtnActionPerformed(evt);
            }
        });

        ecodebtn.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        ecodebtn.setText("SELECT ECODE");
        ecodebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecodebtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        ecodetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecodetfActionPerformed(evt);
            }
        });
        ecodetf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ecodetfFocusLost(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALARY CALCULATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ecodebtn)
                                .addComponent(jLabel11)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ecodecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bptf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(medtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(hratf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ittf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pttf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totearntf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pftf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(calcbtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(savebtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(71, 71, 71)
                                    .addComponent(netpaytf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitbtn)
                            .addComponent(totdedtf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ecodecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hratf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ittf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(totdedtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totearntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(netpaytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecodebtn)
                    .addComponent(calcbtn)
                    .addComponent(exitbtn)
                    .addComponent(savebtn))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection cn=null;
ResultSet rs=null;
Statement stmt=null;
    private void bptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bptfActionPerformed

}//GEN-LAST:event_bptfActionPerformed

    private void bptfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bptfFocusLost

}//GEN-LAST:event_bptfFocusLost

    private void calcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcbtnActionPerformed
      ecodebtn.setEnabled(false);
        double bp = Double.parseDouble(bptf.getText());
       double hra,med,con,pf,it,pt,tern,tded,netpay;
       if (bp==18000)
       {
           pt=200;
           it=0.04*bp;
       }
       else if (bp==15000)
       {
           pt=100;
           it=0.03*bp;
       }
       else if (bp==12000)
       {
           pt=50;
           it=0.02*bp;
       }
       else
       {
           pt=20;
           it=0.01*bp;
       }
       hra = 0.5*bp;
       med =0.2*bp;
       con = 0.3*bp;
       pf=0.83*bp;
       tern=bp+hra+med+con+pf;
       tded=pf+it+pt;
       netpay=tern-tded;
       hratf.setText(""+hra);
       medtf.setText(""+med);
       contf.setText(""+con);
       pftf.setText(""+pf);
       ittf.setText(""+it);
       pttf.setText(""+pt);
       totearntf.setText(""+tern);
       totdedtf.setText(""+tded);
       netpaytf.setText(""+netpay);
        try{
            Class.forName("com.mysql.jdbc.Driver");
cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");

            stmt=cn.createStatement();
            String ec=ecodetf.getText();
            String qry ="Select ecode from empsal where ecode="+ecodetf.getText()+";";
            rs=stmt.executeQuery(qry);
            rs.next();
            System.out.println(rs.getString("ecode"));
            if(rs.getString("ecode").equals(ec))
            {
                jopmsg.showMessageDialog(null,"ecode exists");
                 savebtn.setEnabled(false);           }
                    } catch( Exception e){
                    System.err.println(e);}
    }//GEN-LAST:event_calcbtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       ecodecmb.removeAllItems();
       calcbtn.setEnabled(false);
       ecodetf.setVisible(false);
                try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");
            stmt=cn.createStatement();
            System.out.println("Testing");
            String qry ="Select ecode from info;";
            rs=stmt.executeQuery(qry);
            while(rs.next()) {
                ecodecmb.addItem(rs.getString("ecode"));
            }
        } catch (Exception e){
                    System.err.println(e);}
    }//GEN-LAST:event_formWindowGainedFocus

    private void ecodebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecodebtnActionPerformed
        ecodetf.setText(""+ecodecmb.getSelectedItem());
        try{
            PreparedStatement ps = cn.prepareStatement("Select * from info where ecode=?");
         ps.setString(1,ecodecmb.getSelectedItem().toString());
      //  String qry ="Select * from info where ecode="+ecodecmb.getSelectedItem()+"";
          
        rs=ps.executeQuery();
            
            while(rs.next()) {
                bptf.setText(""+rs.getString("epay"));
                
            }
            calcbtn.setEnabled(true);
        } catch (Exception e){
            System.err.println("calculate="+e);}
}//GEN-LAST:event_ecodebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
      
        empmenu em=new empmenu();
        em.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_exitbtnActionPerformed

    private void ecodetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecodetfActionPerformed
        
    }//GEN-LAST:event_ecodetfActionPerformed

    private void ecodetfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ecodetfFocusLost
     
    }//GEN-LAST:event_ecodetfFocusLost

    private void calcbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calcbtnFocusGained

    }//GEN-LAST:event_calcbtnFocusGained

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");

            PreparedStatement ps = cn.prepareStatement("insert into empsal values(?,?,?,?)");
            
            
            ps.setString(1,ecodetf.getText());
            ps.setString(2,totearntf.getText());
            ps.setString(3, totdedtf.getText());
            ps.setString(4,netpaytf.getText());
            ps.executeUpdate();
            jopmsg.showMessageDialog(null,"Salary ADDED","ADDITION OF RECORDS",1);
            }
            catch( Exception e){
                System.err.println(e);
            }
}//GEN-LAST:event_savebtnActionPerformed

    private void ecodecmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecodecmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecodecmbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bptf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcbtn;
    private javax.swing.JTextField contf;
    private javax.swing.JButton ecodebtn;
    private javax.swing.JComboBox ecodecmb;
    private javax.swing.JTextField ecodetf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField hratf;
    private javax.swing.JTextField ittf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jopmsg;
    private javax.swing.JTextField medtf;
    private javax.swing.JTextField netpaytf;
    private javax.swing.JTextField pftf;
    private javax.swing.JTextField pttf;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField totdedtf;
    private javax.swing.JTextField totearntf;
    // End of variables declaration//GEN-END:variables

}
