package core_java_pro_employee;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * salup.java
 *
 * Created on 4 Dec, 2013, 2:04:05 PM
 */

/**
 *
 * @author Harish
 */
public class salup extends javax.swing.JFrame {

    /** Creates new form salup */
    public salup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopmsg = new javax.swing.JOptionPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ldbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ecodetf = new javax.swing.JTextField();
        bptf = new javax.swing.JTextField();
        medtf = new javax.swing.JTextField();
        hratf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ittf = new javax.swing.JTextField();
        pttf = new javax.swing.JTextField();
        totearntf = new javax.swing.JTextField();
        contf = new javax.swing.JTextField();
        pftf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        calcbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        netpaytf = new javax.swing.JTextField();
        exitbtn = new javax.swing.JButton();
        totdedtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE PAYROLL MANAGEMENT");
        setMinimumSize(new java.awt.Dimension(700, 500));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("EMPLOYEE CODE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("BASIC PAY");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("PROVIDENT FUND");

        ldbtn.setFont(new java.awt.Font("Garamond", 1, 14));
        ldbtn.setText("LOAD DATA");
        ldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldbtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel11.setText("TOTAL EARNINGS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("MEDICAL ALLOWANCE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("HOUSE RENT ALLOWANCE");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("CONVEYANCE ALLOWANCE");

        ecodetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecodetfActionPerformed(evt);
            }
        });
        ecodetf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ecodetfFocusLost(evt);
            }
        });

        bptf.setEditable(false);
        bptf.setToolTipText("");
        bptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bptfActionPerformed(evt);
            }
        });
        bptf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bptfFocusLost(evt);
            }
        });

        medtf.setEditable(false);

        hratf.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("PROFESSIONAL TAX");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setText("INCOME TAX");

        ittf.setEditable(false);

        pttf.setEditable(false);

        totearntf.setEditable(false);

        contf.setEditable(false);

        pftf.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setText("TOTAL DEDUCTIONS");

        calcbtn.setFont(new java.awt.Font("Garamond", 1, 14));
        calcbtn.setText("CALCULATE NET PAY");
        calcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbtnActionPerformed(evt);
            }
        });
        calcbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calcbtnFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel13.setText("NET PAY");

        netpaytf.setEditable(false);

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14));
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        totdedtf.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALARY UPDATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ldbtn)
                        .addGap(28, 28, 28)
                        .addComponent(calcbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addGap(74, 74, 74))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bptf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medtf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hratf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totearntf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pftf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totdedtf, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ittf)
                                        .addComponent(pttf, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(exitbtn))))
                            .addComponent(netpaytf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(contf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totearntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(totdedtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(netpaytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hratf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(ittf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldbtn)
                    .addComponent(calcbtn)
                    .addComponent(exitbtn))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection cn=null;
ResultSet rs=null;
Statement stmt=null;  
private void ldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldbtnActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");

            PreparedStatement ps = cn.prepareStatement("Select epay from info where ecode=?");
            ps.setString(1,ecodetf.getText() );
            rs=ps.executeQuery();
            while(rs.next()) {
                bptf.setText(""+rs.getString("epay"));
            }
            calcbtn.setEnabled(true);
        } catch (Exception e){
        jopmsg.showMessageDialog(null,"ERROR IN CONNECTION","SEARCHING OF RECORDS",0);};
}//GEN-LAST:event_ldbtnActionPerformed

    private void ecodetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecodetfActionPerformed
     


}//GEN-LAST:event_ecodetfActionPerformed

    private void ecodetfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ecodetfFocusLost
   
}//GEN-LAST:event_ecodetfFocusLost

    private void bptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bptfActionPerformed

}//GEN-LAST:event_bptfActionPerformed

    private void bptfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bptfFocusLost
ldbtn.setEnabled(false);
}//GEN-LAST:event_bptfFocusLost

    private void calcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcbtnActionPerformed
        ldbtn.setEnabled(false);
        double bp = Double.parseDouble(bptf.getText());
        double hra,med,con,pf,it,pt,tern,tded,netpay;
        if (bp==18000) {
            pt=200;
            it=0.04*bp;
        } else if (bp==15000) {
            pt=100;
            it=0.03*bp;
        } else if (bp==12000) {
            pt=50;
            it=0.02*bp;
        } else {
            pt=20;
            it=0.01*bp;
        }
        hra = 0.5*bp;
        med =0.2*bp;
        con = 0.3*bp;
        pf=0.83*bp;
        tern=bp+hra+med+con+pf;
        tded=pf+it+pt;
        netpay=tern-tded;
        hratf.setText(""+hra);
        medtf.setText(""+med);
        contf.setText(""+con);
        pftf.setText(""+pf);
        ittf.setText(""+it);
        pttf.setText(""+pt);
        totearntf.setText(""+tern);
        totdedtf.setText(""+tded);
        netpaytf.setText(""+netpay);
        try{
            Class.forName("com.mysql.jdbc.Driver");
cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/core_employee", "root", "root");
PreparedStatement ps  = cn.prepareStatement("Update empsal set gross_sal=?,totded=?,netpay=? where ecode=?");
        ps.setString(1, totearntf.getText());
        ps.setString(2, totdedtf.getText());
        ps.setString(3, netpaytf.getText());
        ps.setString(4, ecodetf.getText());
            ps.executeUpdate();
            jopmsg.showMessageDialog(null,"Salary updated","UPDATION OF RECORDS",1);
            
                      }
         catch( Exception e){
             System.err.println(e);}
}//GEN-LAST:event_calcbtnActionPerformed

    private void calcbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calcbtnFocusGained

}//GEN-LAST:event_calcbtnFocusGained

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        empmenu em=new empmenu();
        em.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_exitbtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bptf;
    private javax.swing.JButton calcbtn;
    private javax.swing.JTextField contf;
    private javax.swing.JTextField ecodetf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField hratf;
    private javax.swing.JTextField ittf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jopmsg;
    private javax.swing.JButton ldbtn;
    private javax.swing.JTextField medtf;
    private javax.swing.JTextField netpaytf;
    private javax.swing.JTextField pftf;
    private javax.swing.JTextField pttf;
    private javax.swing.JTextField totdedtf;
    private javax.swing.JTextField totearntf;
    // End of variables declaration//GEN-END:variables

}
